# Generated by Django 5.1.5 on 2025-01-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('main', 'Wyjściowa 11'), ('rez', 'Rezerwa')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna'), ('I', 'Inne')], max_length=100, null=True)),
                ('position', models.CharField(choices=[('BR', 'Bramkarz'), ('LO', 'Lewy Obrońca'), ('śO', 'Środkowy Obrońca'), ('PO', 'Prawy Obrońca'), ('LS', 'Lewy Skrzydłowy'), ('PS', 'Prawy Skrzydłowy'), ('OP', 'Ofensywny pomoPomocnikcnik'), ('DP', 'Defensywny Pomocnik'), ('ŚP', 'Środkowy Pomocnik'), ('N', 'Napastnik'), ('LN', 'Lewy Napastnik'), ('PN', 'Prawy Napastnik')], max_length=100)),
                ('number', models.PositiveBigIntegerField()),
                ('signing_date', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Legia.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=50)),
                ('game_spot', models.IntegerField(choices=[('Wyjazd', 'Na wyjęździe'), ('Dom', 'U siebie')], null=True)),
                ('game_type', models.IntegerField(choices=[('Liga', 'Liga'), ('Puchar_Kraju', 'Puchar Kraju'), ('CL', 'Champions League'), ('EL', 'Europa League')], null=True)),
                ('date', models.DateField()),
                ('score', models.CharField(max_length=50)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Legia.team')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna'), ('I', 'Inne')], max_length=100, null=True)),
                ('signing_date', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Legia.team')),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('plec', models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mężczyzna'), ('I', 'Inne')], max_length=100, null=True)),
                ('signing_date', models.DateTimeField(auto_now_add=True)),
                ('specialization', models.CharField(max_length=50)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Legia.team')),
            ],
        ),
    ]
