# Generated by Django 5.1.5 on 2025-01-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant',
            options={'ordering': ['lastname']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['lastname']},
        ),
    ]
