# Generated by Django 5.1.5 on 2025-01-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legia', '0002_alter_assistant_options_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
        migrations.AddField(
            model_name='game',
            name='score_legia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score_opponent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='specialization',
            field=models.CharField(choices=[('Trener Bramkarzy', 'Trener Bramkarzy'), ('Trener Obrońców', 'Trener Obrońców'), ('Trener Pomocników', 'Trener Pomocników'), ('Trener Napastników', 'Trener Napastników'), ('Taktyk', 'Taktyk'), ('Trener Motoryczny', 'Trener Motoryczny')], max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_spot',
            field=models.CharField(choices=[('Na wyjeździe', 'Na wyjeździe'), ('U siebie', 'U siebie')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Liga', 'Liga'), ('Puchar Kraju', 'Puchar Kraju'), ('Champions League', 'Champions League'), ('Europa League', 'Europa League'), ('Spotkanie Towarzyskie', 'Spotkanie Towarzyskie')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('Wyjściowa 11', 'Wyjściowa 11'), ('Rezerwa', 'Rezerwa')], max_length=100),
        ),
    ]
