# Generated by Django 5.1.5 on 2025-01-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legia', '0003_alter_game_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team']},
        ),
        migrations.AddField(
            model_name='team',
            name='capacity',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('BR', 'Bramkarz'), ('LO', 'Lewy Obrońca'), ('śO', 'Środkowy Obrońca'), ('PO', 'Prawy Obrońca'), ('LS', 'Lewy Skrzydłowy'), ('PS', 'Prawy Skrzydłowy'), ('OP', 'Ofensywny Pomocnik'), ('DP', 'Defensywny Pomocnik'), ('ŚP', 'Środkowy Pomocnik'), ('N', 'Napastnik'), ('LN', 'Lewy Napastnik'), ('PN', 'Prawy Napastnik')], max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('Wyjściowa 11', 'Wyjściowa 11'), ('Rezerwa', 'Rezerwa'), ('Druga Drużyna', 'Druga Dużyna'), ('Akademia Juniorska', 'Akademia Juniorska')], max_length=100),
        ),
    ]
