# Generated by Django 5.1.5 on 2025-01-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legia', '0004_alter_player_options_team_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team', 'position']},
        ),
    ]
