# Generated by Django 5.1.5 on 2025-01-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Legia', '0008_remove_game_players_alter_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='plec',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='plec',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='plec',
            new_name='gender',
        ),
    ]
